### ISSUE TITLE
Pushing more than 14 modes (orbit) gets reduced to 14 modes

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#12]
You can push less than 14 modes, but not more. If you push more than 14 modes, pulling those modes after will result in a blank mode list.
![image](https://github.com/Unreal-Dan/lightshow.lol/assets/41027005/fbba1ebd-a54a-4012-839e-a9ba87ddc09e)

**Comment by Unreal-Dan** [comment]
technically this is how it's supposed to work, the orbit has it's max modes set to that amount. 

However, we could enhance this, for starters the orbit could have more modes, and then secondarily we can display and/or enforce the max-mode limit in the editors when they are connected to a respective device.
