### ISSUE TITLE
Import mode only applies to the first led

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#13]
When importing a mode the imported settings apply to the first led and the rest are random but match each other. It's as if a new mode is generated randomly then the imported mode overwrites the first led slot.

**Comment by Unreal-Dan** [comment]
that is exactly what happens XD

**Comment by LivingSynthesis** [comment]
I meant it only applies to the first LED rather than the selected LED. There is currently no way to import a mode into any other LED than the first... which is not ideal XD

**Comment by Unreal-Dan** [comment]
should be fixed in led indicator image #15
