### ISSUE TITLE
Color picker isn't able to accept some hex codes

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#3]
EDIT: The current color picker cannot recognize capital letters, you must type them in lower case and allow it to correct them for you. JFC -.-

For instance you cannot enter #FF6C00

![image](https://github.com/Unreal-Dan/lightshow.lol/assets/41027005/0dc44adc-ad81-429d-b56a-e8bfa3fd1674)

**Comment by Unreal-Dan** [comment]
should be fixed with new color picker
