### ISSUE TITLE
Colors missing from color pickers slider

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#45]
![image](https://github.com/user-attachments/assets/0b7f866a-5da0-45d7-8a50-3be4bc1820f6)
The vertical hue slider stops at 255, 0, 15. It should go at least to 255,0,1 if not 255, 0, 0.

**Comment by Unreal-Dan** [comment]
here is the position of 255 0 0:
![image](https://github.com/user-attachments/assets/2ff068e5-e7ae-4913-ade7-9e4897db7b6c)
