### ISSUE TITLE
Create UI buttons for 1,2,3,4 lightshow actions so the hotkeys won't interfere with inputs

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#46]
![image](https://github.com/user-attachments/assets/5de7a6f0-8e57-4569-bca2-2f7f7d0bf873)

1. Typing in the hex box sends the cursor to the end of the line after typing a single character as if you pressed the end key
2. Zeros are added from the left when you backspace characters in this field.
3. Pressing keys like 1,2,3, or 4 to enter a number in this field also changes the draw shape of the trail render.

**Comment by Unreal-Dan** [comment]
The 1 2 3 4 actions need to be moved to actual UI buttons, so as to make them available to mobile in the future.
The key events were just a temporary solution to make the patterns usable now. 

The hex box does that so when you paste a hex number in it jumps to the right and pushes everything else off to the left that was already there. It's designed specifically for people to paste hex codes into, not for people to manually edit components of the color.  They have decimal inputs and sliders for that.

Renaming for the 1234 hotkey issue, the hex box is a non-issue I think.
