### ISSUE TITLE
If you attempt to push a mode while previewing this mode, it crashes the device.

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#52]
Pretty straight forward. If you push while previewing this the device crashes. It will push successfully if you are previewing something else though

{"flags":10,"num_leds":28,"single_pats":[{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26},{"args":[1,3,10,0,2],"colorset":["0xff0033","0xff0033","0xdb2f00","0xb76b00","0x938d00","0x4a6f00","0x164b00","0x002702"],"flags":0,"numColors":8,"pattern_id":14},{"args":[6,6,0,0,0,10,0],"colorset":["0x554a00","0x554a00","0x00aa90","0x00aa90","0xd200ff","0xd200ff"],"flags":0,"numColors":6,"pattern_id":26}]}

**Comment by Unreal-Dan** [comment]
Was able to reproduce this before, but trouble reproducing now... god damn

**Comment by Unreal-Dan** [comment]
fixed in https://github.com/Unreal-Dan/lightshow.lol/pull/54
