### ISSUE TITLE
Possibly Unintentional behavior? Selecting Pattern None clears color set

### ISSUE THREAD

**Issue by LivingSynthesis** [Unreal-Dan/lightshow.lol#9]
After selecting pattern none, the color set is discarded. This makes sense but is inconvenient if it could easily be preserved instead.
![image](https://github.com/Unreal-Dan/lightshow.lol/assets/41027005/8af46588-c0ab-4ddf-8230-1f648a48591d)

**Comment by Unreal-Dan** [comment]
actually none shouldn't be at the bottom, should be easy to remove it

**Comment by Unreal-Dan** [comment]
none is cleaned up and gone now
